### ISSUE TITLE
Rinbery ???

### ISSUE THREAD

**Issue by symulacr** [Orbiter-Finance/OrbiterX-contract#1]
Hi, I'm writing to you about a very thorny problem.

I carried out a transaction from your testnet bridge portal. In two transactions, for a total of 10 ETH from Sepolia for Scroll Sepolia.

It's almost 6 hours now and I still haven't received anything. My balance on Scroll Sepolia is still zero.

I would like to ask you to help me recover my tokens to the limit.

Thank you

Also, from Taiko for Scroll Sepolia

there is a problem with taiko's rpc

**Comment by Stargazerr1** [comment]
I had lost a lot of coins in some scam case just like this thanks to the best hacker in the world who helped me recover all my funds,message him on telegram his telegram username is [https://t.me/Blackhathacker11](https://t.me/Blackhathacker110)

**Comment by kakui-lau** [comment]
You can try to contact the administrator in the discord community~
