### ISSUE TITLE
orbiter.finance my bridge action is not coming to my account

### ISSUE THREAD

**Issue by kenan012709** [Orbiter-Finance/OrbiterX-contract#2]
The operation that I want to perform from the base network to the etherum network did not occur, but it seems to have taken place in explore. My transaction is not visible in orbiter finance transaction history. I want my money back to me
![basescan](https://github.com/Orbiter-Finance/OrbiterX-contract/assets/134808040/8128d4ef-a7c8-4f9f-a65c-5b36280c63cc)
![exstra orbirter](https://github.com/Orbiter-Finance/OrbiterX-contract/assets/134808040/77c33c6c-c9a5-4fcc-ba36-bb5f9378186c)
![orbiter history](https://github.com/Orbiter-Finance/OrbiterX-contract/assets/134808040/fa6c0dcd-fea9-4ea7-8497-aa3ac619b4cb)

basescan
orbirter finance history
exstra

**Comment by kenan012709** [comment]
![basescan2](https://github.com/Orbiter-Finance/OrbiterX-contract/assets/134808040/9d5ebddb-080a-4cce-a0f7-5a1a552a780a)

**Comment by kakui-lau** [comment]
The amount of your transaction for the transfer lacks the so-called destination network identification code. Read more about it in the documentation. It says that in this case the transaction will not be executed.
But you can contact the official to return it
https://docs.orbiter.finance/orbiterfinancesbridgeprotocol
